#!/bin/sh

# cfg
LP="/dev/mmcblk1p1" # luks partition
LM="mmc1"           # luks mapper name
CR="/.debian"       # chroot dir


if [ $(id -u) -ne 0 ]; then
  echo "-err: you are not root"
  exit
fi

case $1 in
  on)
    echo "on"
    ;;
  off)
    echo "off"
    ;;
  *)
    echo "usage: $0 <action>"
    echo "  on - setup and chroot to debian"
    echo "  off - close chroot"
    ;;
esac
