#!/bin/sh

# cfg
LP="/dev/mmcblk1p1" # luks partition
LM="mmc1"           # luks mapper name
CR="/.debian"       # chroot dir


if [ $(id -u) -ne 0 ]; then
  echo "-err: you are not root"
  exit
fi

# FIXME: rearrange with functions
case $1 in
  on)
    # load modules
    modprobe dm_mod
    modprobe dm_crypt
    modprobe dm_loop
    # check if we already open
    if [ -e /dev/mapper/${LM} ]; then
      echo "$LM already mapped..."
    else
      cryptsetup luksOpen $LP $LM
    fi
    qchroot /dev/mapper/${LM} $CR
    ;;
  off)
    closechroot
    if [ -e /dev/mapper/${LM} ]; then
      echo "luksClose $LM..."
      cryptsetup luksClose $LM
    else
      echo "$LM not mapped..."
    fi
    ;;
  *)
    echo "usage: $(basename $0) <action>"
    echo "  on - enable and chroot"
    echo "  off - disable and close"
    ;;
esac
