#!/bin/sh

LP="/dev/mmcblk1p1" # luks partition
LM="mmc1"           # luks mapper name

# load modules
modprobe dm_mod
modprobe dm_crypt
modprobe dm_loop

# check if we already open
if [ -e /dev/mapper/${LM} ]
then
  echo "$LM already mapped..."
else
  cryptsetup luksOpen $LP $LM
fi
debian
