#!/bin/bash

# newguy - network observer and guesser

T=60 # default timeout, adjustable via options later
TS=$(date +%Y%m%d-%H%M%S) # timestamp

# gear
TCPDUMP="/usr/sbin/tcpdump"
TSHARK="/usr/bin/tshark"
CAPINFOS="/usr/bin/capinfos"
# FIXME: check if we are good to go

usage() {
    echo
    echo "usage: $0 [options] <interface>|<file>"
    echo "options:"
    echo " -n          don't parse, save only"
    echo " -t <time>   time in sec (default 60)"
    echo
    exit
}

# get options if any
while getopts "nt:" opt; do
    case $opt in
        n)
            SAVEONLY=1
            ;;
        t)
            T=$OPTARG
            ;;
        \?)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# usage if no args
[  $# -eq 0 ] && usage

# check if our argument is an interface or a file
if /sbin/ifconfig $1 > /dev/null 2>&1; then
    echo "--- capturing for ${T} seconds on $1 ..."
    FN="${TS}-${1}-${T}s.cap"
    timeout ${T} ${TCPDUMP} -i $1 -w ${FN} -s0
    # older versions of timeout don't support
    # '--preserve-status', so, using dirty hack
    [ $? -eq 124 ] || exit
    echo
else
    FN=$1
    [ -e $FN ] || {
      echo "no such file or interface"
      exit
    }
fi
echo "--- capture file:"
${CAPINFOS} -csuaeEix ${FN} || exit
echo

#we have a valid pcap file we can work with
# should we?
[[ $SAVEONLY ]] && exit

echo "--- protocol hierarchy:"
${TSHARK} -r ${FN} -q -zio,phs 2>/dev/null | egrep -v '^$|^==|^Filter:|Protocol'
echo

# CDP or LLDP
echo "--- CDP or LLDP:"
${TCPDUMP} -r ${FN} -v -c 1 '(ether[12:2]=0x88cc or ether[20:2]=0x2000)' 2>/dev/null
echo
