#!/bin/bash

# newguy - network observer and guesser

T=60 # default timeout, adjustable via options later
TS=$(date +%Y%m%d%H%M%S) # timestamp

# usage if no args
if [  $# -eq 0 ]; then
    echo "usage: $0 <interface>|<file>"
    exit
fi

# check if our argument is an interface or a file
if ip link show dev $1 > /dev/null 2>&1; then
    echo "capturing for ${T} seconds on $1 ..."
    FN="${TS}_${T}s.cap"
    timeout --preserve-status ${T} tcpdump -i $1 -w ${FN} -s0 || exit
    echo "----------"
else
    FN=$1
    [ -e $FN ] || {
      echo "no such file or interface"
      exit
    }
fi

capinfos -csuaeix ${FN} || exit
echo "----------"

#we have a valid pcap file we can work with

