#!/bin/bash
# qp - n900 helper script

# default mobile data id
G="T-Mobile"
# default wifi id
W="0000-000-000"
# check with
# gconftool -R /system/osso/connectivity/IAP

case $1 in
g+)
    # connect 3G
    echo "enabling radio..."
    dbus-send --system --type=method_call --dest=com.nokia.phone.SSC /com/nokia/phone/SSC com.nokia.phone.SSC.set_radio boolean:true
    #sleep 3
    # be cool, check reg status
    s=1
    while [ "$s" -ne "0" ]
    do
        s=$(dbus-send --system --print-reply --dest=com.nokia.phone.net /com/nokia/phone/net Phone.Net.get_registration_status | grep byte | head -1);
        s=${s: -1}
        echo -n "."
        sleep 1
    done
    echo
    echo "connecting 3G ..."
    dbus-send --system --type=method_call --dest=com.nokia.icd /com/nokia/icd com.nokia.icd.connect string:${G} uint32:0
    ;;
g-)
    # disconnect 3G
    echo "disconnecting 3G ..."
    dbus-send --system --dest=com.nokia.icd /com/nokia/icd_ui com.nokia.icd_ui.disconnect boolean:true
    sleep 1
    echo "disabling radio..."
    dbus-send --system --type=method_call --dest=com.nokia.phone.SSC /com/nokia/phone/SSC com.nokia.phone.SSC.set_radio boolean:false
    ;;
w+)
    # connect wifi
    dbus-send --system --type=method_call --dest=com.nokia.icd /com/nokia/icd com.nokia.icd.connect string:${W} uint32:0
    ;;
w-)
    # disconnect wifi
    dbus-send --system --dest=com.nokia.icd /com/nokia/icd_ui com.nokia.icd_ui.disconnect boolean:true
    ;;
n)
    # network status - active interfaces
    ifconfig | (egrep '^wlan|^gprs|^usb' || echo 'none') | cut -d' ' -f1 | xargs
    ;;
b)
    # battery status
    # 
    if which i2cget > /dev/null; then
      # we have i2c-tools
      CSOC=$(($(i2cget -y 2 0x55 0x2c)))  # CSOC Compensated state of charge %. CACT/LMD * 100
      #RSOC=$(($(i2cget -y 2 0x55 0x0b))) # RSOC Relative state of charge %. NAC/LMD * 100
      TTE=$(($(i2cget -y 2 0x55 0x16 w))) # TTE Time to Empty minutes. 65535 if charging.
      TTF=$(($(i2cget -y 2 0x55 0x18 w))) # TTF Time to Full minutes. 65535 if no charging.`
      echo -n "${CSOC}% "
      if [ $TTE = 65535 ]; then
        # charging
        echo "charging, $TTF min. to full."
      else
        echo "discharding, $TTE min. to empty."
      fi
    else
      echo "i2cget not available, install i2c-tools package"
    fi
    ;;
    
l)
    # lock
    # this one is simple lock, just blanking the screen:
    # dbus-send --system --type=method_call --dest=com.nokia.mce /com/nokia/mce/request com.nokia.mce.request.req_tklock_mode_change string:"locked"
    # this one is code-lock:
    dbus-send --print-reply --system --type=method_call --dest=com.nokia.system_ui /com/nokia/system_ui/request com.nokia.system_ui.request.devlock_open \
                                            string:'com.nokia.mce' \
                                            string:'/com/nokia/mce/request' \
                                            string:'com.nokia.mce.request' \
                                            string:'devlock_callback' \
                                            uint32:'3'
    ;;
q)
    # shutdown
    dbus-send --system --type=method_call --dest=com.nokia.dsme --print-reply /com/nokia/dsme/request com.nokia.dsme.request.req_shutdown
    ;;
*)
    # usage
    echo "usage: $(basename $0) <command>"
    echo "commands:"
    echo "g+  connect 3G"
    echo "g-  disconnect 3G"
    echo "w+  connect wifi"
    echo "w-  disconnect wifi"
    echo "n   network status"
    echo "b   battery status"
    echo "l   lock"
    echo "q   shutdown"
    ;;
esac

# for n900/maemo dbus samples
# see http://wiki.maemo.org/User:Jebba/DBUS
