#!/bin/sh
# qp - n900 helper script

# default mobile data id
#G="T-Mobile"
# default wifi id
#W="00000000-dead-beaf-1337-00000"
# check with
# gconftool -R /system/osso/connectivity/IAP
#
# dump/load approach:
# gconftool --dump /system/osso/connectivity/IAP/T-Mobile > conn-mobiledata.gconf
# gconftool --dump /system/osso/connectivity/IAP/00000000-dead-beaf-1337-00000 > conn-wifi.gconf
# Etit ID's to short unified names,
# gconftool --load conn-mobiledata.gconf
# gconftool --load conn-wifi.gconf
# use cross-device compatible neural id's
G="MobileData"
W="DefaultWifi"
# then remove leftouts
# gconftool -R /system/osso/connectivity/IAP | grep "^ /" | egrep -v "MobileData|DefaultWifi" | sed 's/:$//' | while read line; do gconftool --dump ${line} | gconftool --unload -; done
# reuse resulting connectivity gconf fils on other devices

case $1 in
g+)
    # connect 3G
    echo "enabling radio..."
    dbus-send --system --type=method_call --dest=com.nokia.phone.SSC \
        /com/nokia/phone/SSC \
        com.nokia.phone.SSC.set_radio \
        boolean:true
    # be cool, check reg status
    s=1
    while [ "$s" -ne "0" ]
    do
        s=$(dbus-send --system --print-reply --dest=com.nokia.phone.net /com/nokia/phone/net Phone.Net.get_registration_status | grep byte | head -1 | tail -c 2);
        echo -n "."
        sleep 1
    done
    echo
    echo "connecting 3G ..."
    dbus-send --system --type=method_call --dest=com.nokia.icd \
        /com/nokia/icd \
        com.nokia.icd.connect \
        string:${G} \
        uint32:0
    ;;
g-)
    # disconnect 3G
    echo "disconnecting 3G ..."
    dbus-send --system --dest=com.nokia.icd \
        /com/nokia/icd_ui \
        com.nokia.icd_ui.disconnect \
        boolean:true
    sleep 1
    echo "disabling radio..."
    dbus-send --system --type=method_call --dest=com.nokia.phone.SSC \
        /com/nokia/phone/SSC \
        com.nokia.phone.SSC.set_radio \
        boolean:false
    ;;
w+)
    # connect wifi
    dbus-send --system --type=method_call --dest=com.nokia.icd \
        /com/nokia/icd \
        com.nokia.icd.connect \
        string:${W} \
        uint32:0
    ;;
w-)
    # disconnect wifi
    dbus-send --system --dest=com.nokia.icd \
        /com/nokia/icd_ui \
        com.nokia.icd_ui.disconnect \
        boolean:true
    ;;
n)
    # network status - active interfaces
    ifconfig | (egrep '^wlan|^gprs|^usb' || echo 'none') | \
        cut -d' ' -f1 | xargs
    ;;
b)
    # battery status
    # based on
    # https://wiki.maemo.org/N900_Hardware_Charge_Meter/bq-script
    # kernel module independent, speaks hw directly via i2c
    if which i2cget > /dev/null; then
      # we have i2c-tools
      CSOC=$(($(i2cget -y 2 0x55 0x2c)))  # CSOC Compensated state of charge %. CACT/LMD * 100
      TTE=$(($(i2cget -y 2 0x55 0x16 w))) # TTE Time to Empty minutes. 65535 if charging.
      TTF=$(($(i2cget -y 2 0x55 0x18 w))) # TTF Time to Full minutes. 65535 if no charging.`
      echo -n "${CSOC}% "
      if [ $TTE = 65535 ]; then
        # charging
        echo "charging, $TTF min. to full."
      else
        echo "discharding, $TTE min. to empty."
      fi
    else
      echo "i2cget not available, install i2c-tools package"
    fi
    ;;
    
l)
    # lock
    # this one is code-lock
    dbus-send --system --type=method_call --dest=com.nokia.system_ui \
        /com/nokia/system_ui/request \
        com.nokia.system_ui.request.devlock_open \
        string:'com.nokia.mce' \
        string:'/com/nokia/mce/request' \
        string:'com.nokia.mce.request' \
        string:'devlock_callback' \
        uint32:'3'
    # this one also locks power button:
    dbus-send --system --type=method_call --dest=com.nokia.mce \
        /com/nokia/mce/request \
        com.nokia.mce.request.devlock_callback\
        int32:0
    # this one blanks the screen afterwards
    dbus-send --system --type=method_call --dest=com.nokia.mce \
        /com/nokia/mce/request \
        com.nokia.mce.request.req_tklock_mode_change \
        string:"locked"
    ;;
q)
    # shutdown
    dbus-send --system --type=method_call --dest=com.nokia.dsme \
        /com/nokia/dsme/request \
        com.nokia.dsme.request.req_shutdown
    ;;
*)
    # usage
    echo "usage: $(basename $0) <command>"
    echo "commands:"
    echo "g+  connect 3G"
    echo "g-  disconnect 3G"
    echo "w+  connect wifi"
    echo "w-  disconnect wifi"
    echo "n   network status"
    echo "b   battery status"
    echo "l   lock"
    echo "q   shutdown"
    ;;
esac

# for n900/maemo dbus samples
# see http://wiki.maemo.org/User:Jebba/DBUS
# https://wiki.maemo.org/Phone_control
