#!/bin/bash
# battery usage reporter for tmux statusbar under native Debian on n900

# basedir
BD="/sys/class/power_supply/bq27200-0"

# 'X' means 'uncalibrated'
CAP=$(cat ${BD}/capacity 2>/dev/null || echo "X")
ST=${BD}/status}
if grep Charging ${BD}/status > /dev/null; then
  ST="+"
else
  ST=""
fi

if [ "$CAP" == "X" ]; then
  # battery is uncalibrated
  TT="N/A"
else
  if [ "$ST" == "+" ]; then
    TT=$(date -d@$(cat ${BD}/time_to_full_now) -u +%H:%M)
  else
    TT=$(date -d@$(cat ${BD}/time_to_empty_now) -u +%H:%M)
  fi
fi
echo "${ST}${CAP}%(${TT})"
